kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: quay-intg
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  labels:
    codefresh.io/entity: integration-secret
    codefresh.io/integration-name: quay-intg
    codefresh.io/integration-type: registry.quay
spec:
  template:
    metadata:
      name: quay-intg
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
    data: null
  encryptedData:
    password: >-
      AgCWweuwYosb7u+r1EROyWB7/5umZZy7qRv+gKyY8ATsw+39dFdD+e8SCoSo0Nr0v5i6JzisZuiayimn9j/0mKEt5+l8o0BEbycl1GRz2u1fAO1Cu4PiaVMymaO2cU3+LqgcTFNV/k9flODEN03IVYjqZjQVil6DXuQwRQd4WK8smeJvGpfPpwQR0hp0N8JQjE0hrN6/ZEb8KEoAdExXgQELWH4+6Jte4h2/NKEFZTZGl2ABO9gMbQvRMhrhq5hFW6h6QiwjvTwE/tfVnMX7LO0hTEqKW5cLDleuSm55J9j01GzvJVJ5gdA9Ku+WvGk5mpnUXfhAzZBJW76ij11BgMnakkZxgc0uz0G+XSV/aK6CJnqYgzxvRzUXMmRiuHCj3Opqbn55MDVUebt31GuuNFT2nas5qWbbQ9DD/4fSUotpdlg9fkJK/eKW0DWcKk1VsXl91vCZzx6Jqhagni15ka6I8uDrmeKAywJq/s90tIAuoE7naVIZTP8K9T2R9gAyxU/2aY2X5kjFoF6rL2kFsxMfZt4HBcRffyHtIogiqTZYU/3Rv0/Uf3gIIVUt/XasbA4EILFjPzlGlzleXXNv6Q891RmJe8MLuI0oqbGKhVFQzn3IpFBOem6s0zQnIeo8qC12PvmOiSXxaiyoVJoYkAAj/h8mCfznvGNCbK1Fofgi0rkot9kRWd8/hyidB3Rzaf/AxZFtCXArLPPqdLs8vxsd9dIlXf3AndL3Lc7nxQ==
