apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd-autopilot.argoproj-labs.io/default-dest-server: https://F6CCE3BD7B6163A01396BFFF61A7BB0C.gr7.us-east-1.eks.amazonaws.com
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-wave: "-2"
  creationTimestamp: null
  name: prod
  namespace: prod
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: prod project to simulate prod environment
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
status: {}
