kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: jira-intg
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  labels:
    codefresh.io/entity: integration-secret
    codefresh.io/integration-name: jira-intg
    codefresh.io/integration-type: issue.jira
spec:
  template:
    metadata:
      name: jira-intg
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
    data: null
  encryptedData:
    api_token: >-
      AgALIe84n0mzh6VnYFNeqtojWLtqHDIfjoK8usbyR6057Wp3B29y9zjcBDvn24jo9BsxKPNTkUqxT2RXG9Eh7nZLijEZIeWA9Ae2qSbGUBGUaxui6cEuV6eG6rHLOx8JilRw2vzTV8kXarRIDis3CGLskpDKOKbNyuCMkL+SVoNF2hU8ATBYmKxdyDWxcyiuaQtqUuXf5m8ezgs0X2cWFe1hEufqZsS9LY3V9ac/H9DDKDo3cbcjC34z5jK88YBg+jxd8t+myB/2LFdUE6DRcIZk4KTwGxoB5okN4nMHwNQemLOrvbs7SYFa2/dy0Z3xsfeCx/FKtPC86fcyQoyS1Mbwrv11BSOiAtM+BIVAl78DI6yWlcpXGrr5zc8WnMvMlWUmD+oSBvPc0jWFUfixwKurhH2ZpOgBwBlB0traz6BEYwX+w8Ucy+jbLY4bb7izBOJZbKevH+wXDE5l6VwYRya3BcUPl/GnzIyIJOtEL0ugNTKREXL3DSk0YRUW5bKWmlfUXdk72Q7zNhv2vpeHeRInxgj/RgJdsiQqJQlIFefpmHbfUFX7xmlxuhratAEDkfbUVT50Dwl55lx1mHT7MfVVnbyrrIbQ1+zg7X7PjcE262dPvxhIcNDrniIvm83GsnqKVOpBxX9OQU6Tu6euObmb4tzGRJiVoqYBmnq/jEyB8I6Ykhh63lMd46dYhp5h5oWVcwUyPx7IgLKXBvZAzOpj9+Mj8hQ7rRs=
