apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gke-apps
  labels:
    codefresh.io/entity: 'git-source'
    codefresh.io/internal: 'false'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lrochette/csdp_applications.git
    path: ./apps/gke
    targetRevision: main
    directory:
      include: '*'
      exclude: ''
      recurse: true
  destination:
    namespace: gke-csdp
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
