kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: docker-lr
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  labels:
    codefresh.io/entity: integration-secret
    codefresh.io/integration-name: docker-lr
    codefresh.io/integration-type: registry.dockerhub
spec:
  template:
    metadata:
      name: docker-lr
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
    data: null
  encryptedData:
    password: >-
      AgA9sWBbTd8pxhJto096l4XXsJUeo2eWnSQKhPa+TziMUH6cSx2I1GMIUuTaaub2xxIjfUDZoUDt4w872GhX3YEr+vjMtPbIsrrltZA9Vl2TvKmKRf1A9IuxEv/Y61XpcP7nUJHSUt0dyY8oRRmEFWEQOYgUSjTdsqz7zsAB5z/G5dtL87MsFxLtevwD+QUvQzowyIDqhuHv+qvA4jLMC2+veUkp2xWNZF6pLiNhNhq8nHYo+wMJVMfbA56Fi+Qa2mbVf59w7JfewUhq/oZtUEIeuqi+Wwn2PenuoSZ5uTFbwQTi5fIDznPV1P84WaRsapUVLe2aVdeKhqExUIrH6ejCDwHPPNTiiH4pbX35YF7O52w1dSyxu2wjZIhrWX9tg+xminVC0toLDn587RwaH0idHuiPsuV5Lco6mAWEIcSxTwAzncOtymU9BXp3LK+/f3Lk5jRuXVEKNWz4AT8OI80/a5TxC0W8Wmme+hI85WqBajp3wXkCZdomaxWgN8+dyalD/orrhWexJgeBP4kjTU8s93lSFFphvPUpn8JTmBeo00ZYjs7lRk8XV5Y9DpC64pgkyEu1MtlSjHw/rtrC+/Nj9F5eyMdsLjKflfS6nb29+Y1ldgEADTKTJVIOmJgIULrB4aSVslsn/+Aq8EBUItv8//62YZcUT8m5Y5u/TLPF0ehR/++bvkHxOT4vRyQr8HkqtgcSc27dgzwPz3M7TK6WG4Cqy8EX+Azfea+wm3Mng8R4b24=
