kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: docker-lr
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  labels:
    codefresh.io/entity: integration-secret
    codefresh.io/integration-name: docker-lr
    codefresh.io/integration-type: registry.dockerhub
spec:
  template:
    metadata:
      name: docker-lr
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
    data: null
  encryptedData:
    password: >-
      AgAYrzIgmmT19UApDtscnCH0d+q9xzxWK5SybvCNLwyi1n/BQ+Nni/4BPtCpjoDs8CsHTEtQsp3sDqYYyLi2myQaZy2zWBi8Cc4wUqd8UwUKpRA7RbPdpWAf4tBKwCDPVhVdN6HY2OLVtOVt47FlvIgBangX52DCw226mWpj+Q2zuVzzRelopjeD7xLosFyhC+5HiCfuQtk3HfibXUpr0Zqr0HC1meeEh1X33a6vOnBB9A4zEfT9hhMealmhAhP/PB0f5cZ4Q7uvBfHE5y95kJ4/3nVWB6bKCVoeoYhxx8758jImPLWvp+QgkibVxy7Eb2qc7evxzItUNY+yEp1WvzK076D4NC5wwE/zHdK/gA/HWBJ+2fFnm4P9/bW179Ut10obED034f/NANwGSFT5cCxwwxN6Z9/jYYzaTbYD79pxatUF1Y2yJBlcXxdJfby4vyZstX4FdZYuaMXZgllXHTaOGqqdIfBgdSWAd2kl65Yh48URlQcdIreZg8cRkZupn9rvDq0SekyFxSow37aBkUoL+VqDND82jvmWI0RtLtvb/HJKYEEmwat8HuMouCj/m9dsmf7X8K44z8+T4nXWpFVFsEnYTI+p5zxg+SM82MTdb4Ye1zafE0MPI5TlvuI6x77pth96mYDo3LnNruw6T8om89LwCSV1GlakgnLNP7DjM2XE+Fsq8aYjPnl1er7iQQEqpDPNWdSaxgDmUIM=
