apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- behavior: merge
  literals:
  - argoWorkflowsInsecure=true
  - cfHost=https://g.codefresh.io
  - cors=https://g.codefresh.io
  - env=production
  name: cap-app-proxy-cm
kind: Kustomization
namespace: csdp
resources:
- ../../base

# For Helmfile support?
patches:
  - target:
      name: argocd-cm
      kind: ConfigMap
      version: v1
    patch: |-
      - op: add
        path: /data/kustomize.buildOptions
        value: --enable-helm
