kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: docker-intg
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  labels:
    codefresh.io/entity: integration-secret
    codefresh.io/integration-name: docker-intg
    codefresh.io/integration-type: registry.dockerhub
spec:
  template:
    metadata:
      name: docker-intg
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
    data: null
  encryptedData:
    password: >-
      AgCyT6x+FwWS8N8RRv+HJHuF1sqOuDD5VLYWbe/n8FLhgjm29EyXzvQ0M0xxIxx4eP9yFGWpHeas5jg30E+XJkzuTh4FW5O3kzB4COMGzRzjBCl8P6y7XYxuhnpZtxn4qmlz4lRdsbEJW3V+jHfAV5R08hm9SXaMcUFpei0S9RfEGwErjmf+CTQ5DKgJh2li7o6ZY+1yLBwW1kfNmNMb9JWZ1wKFGZyajNtR07y1PAtLUTmxk73CLd1hQScmUs4t7WI/2fOT+4dnRZNSlazp2h+JA20vVJfusuosjk5Z4rIpKxQzXHNcQzARATT0mokSM5UGIJXHtW1xoA5NKOi60EvzOmjlB3AjQs5wnPFHwHUCfv/h2Otua6uindHlSGOUfNXp7a5hOAIiyXNemwKTJCtPyNX4hXHfsf5bs3s7Tgks48PTNGhCtLj6e8DDkWeHJIE7Jkh0nn+KJJ9ahoqzKpZMtPZVUarIIOayQkLpjmM5I0UQlq2vGvwwUNoGwLo1UAFIHhfnhZm8OS+FH+Q08i5NnxXkJMneJNWCS9VPDff2WE2n6ZmNDJXMhG/sVS7ZM/tjiv48uWFhtwOvmeYSyHEGjulNDrCHXhgdPIRBU9cIJfI6vzNTVKWfc3arMA0KuLfa5AxZCnn1Ciuk2AjqVjWgSMz82hfmqzqEwhDI/D+TC62hEm+O+epSjA/oh9kufo9ts4PrriIZCBys+3s=
