kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: jira-lr
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  labels:
    codefresh.io/entity: integration-secret
    codefresh.io/integration-name: jira-lr
    codefresh.io/integration-type: issue.jira
spec:
  template:
    metadata:
      name: jira-lr
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
    data: null
  encryptedData:
    api_token: >-
      AgCaDmE91gTfddA4HOkS5uq45PqHy+9tzaYYjK1tClVORG1OC512haN9U9tvaYJtiesMx33AEDHP81DWLcnxfu1ZOQbl444pHhsWapx4LEow8b0m1Q+VMNWOpjUhDTduauvo0+7Yx7fKFosiKs/15PhnR/oYu+v2GWlEuOZu5yRQ0zfQ4JYHomEjl90J557fySu5YstaLJgHqHIuAe4QTpIy7N9KYdfMq9jZYk01nbVTHZhWjq6rS+BJIKpBqeMV++pz88pMEzG2JKuLyhoamyHDJBvInnB8V6YsNkoNK2da6h+HKUHu5NKQ7WH+Sw+vSkzyDbmOfReSCdX1GCusVZRbEU1nPL3AdQuXSB7RdVrrZ7GPcLmQKNmDdAayx/C/vXb3sL25ZNZSORrnyYbipLrHDSka/VDvVmLu8U82Gc+ggbTVfkUxn36POJUrHOKlAqWEqpQBafNmNIHKWOVEXfU4z26/8b57d+hRYjmbkzxCNj0+orST1VDlXEhzWM8sObpMb39ZIOcIkSvgQ/24SSa5CZlvComx5SIoEgXHc8FhfKG11HjDnbKWJU1MwaoPSNk2oTPQjvGfdMkIz1oZjlpfOLDZ7HPkTckBpKjdamJ5YTcVTDSpUiAAI5UtWVX3FzOlIdBFhBEqrhsdjxRa8uzOcOPZNjVkQONGN6d/m65C4tlpNQu+edwkdX91/uVAoyHUIdrcmhuOkH6HpnyXx07UUdSECk5LToY=
