kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: jira-lr
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  labels:
    codefresh.io/entity: integration-secret
    codefresh.io/integration-name: jira-lr
    codefresh.io/integration-type: issue.jira
spec:
  template:
    metadata:
      name: jira-lr
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
    data: null
  encryptedData:
    api_token: >-
      AgDZhbGK43YtKVupHV2k4mI4WM8nVAugM1zSLYio+Tn+cBRlpG4/gQcW3vZpJ3w2fW81Z7T5M/iKjFbDH2xOofcZj9N3W2eh4RVpr5WY5reIrey1LEdPZKJ7CUuOec/utpk4teh3kj+jxuJrE+VdXDV0yaYhJiOrHpQq/9u3ydcl+RPshnXhilY2K41jThdnD96Xd+SF/0CU5zokE367qeylDLe0gQmqOIsfcmMlBJT9bbyFv2Z5sUPQ29d9Qa5MCx9KU6D/MtKxfbp1jR3p970FruFyJys0vCt1oJAaZ1uCONYpGJ2E3QCX6iGel5t6qqi49wgIzw8VClB2QzslSnKlNcQdyoAm/F4frHconzMdFPmhwvbmjNBkX2EtMDqD/affpgzsliY0LIioSZSfcIztyMWwSasa1KTNWLfmpcNPRMThWoCAiOrlkxHIh4/OVDvGKXOp7yUF/sFKNmGVCVOqlLFJ7UKNSq23c8TJ8w4ICecM1c6hweo4iOvpd8f9KjhQ6s/x11E+Ut8BqXB7NTNnbpJbDZ2N19Xg0XAKngJB/NrPUgXa6NiuuK7fSCcAiCTJZDY5xwGsHTaweYoFzFJ1rgkPRIRYb2d2qVwydqZCKlrU8xg9uaTIbuH/LO3+a3xDPwfs1arDAKQn8Yzzyh2kyjHsEHnjES4k2KT56tdlKWxFhcF6X1jte7gAyuY1E9jSdG3R9vIEWQ8vHHxx4cn30EM9oGipQEA=
