kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: jira
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  labels:
    codefresh.io/entity: integration-secret
    codefresh.io/integration-name: jira
    codefresh.io/integration-type: issue.jira
spec:
  template:
    metadata:
      name: jira
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
    data: null
  encryptedData:
    api_token: >-
      AgDIOKxHxhB+Ad55UQmU+YisKIQEKcgTpXOmAPKsGf5B3HDuLdL5oBdPhYU/BQbytKN/CXyk1oMQ20U1QAegIuuTP/A8h/ouwgxu/yIlAPqR6A5bRUrgJKtSkGaBCBKcR3xu9CLu3Wmh1bdO7gwQeuqhHAM6Fm3oiDlLEXqZkmEXP+NhVvSPab1ddLiQaMdATE5enlR0cyqo6SYVDbD9PWzAtMHTy0/fztkbRqlQeZedb24FUB3M0mk3r372e0AVH2X86QjDWnM399MC8l9m2BK+/s1dPV2kteZreTTFXMVimTrbrSk7waUI4D281d5kbmWVrYzuSsbc4bx0QPTnat5JOXxyn7+WEHMIEnYErAuLUmPzBHyZD4pLTEr+M+EXDQWH6+sbRuPtBRLReN58AYQSKvdzB0Qyxa5OKBXJvrvp4SkcYk7faXM1uJ0qC3uC8SRBP/J7gS18Yf8jTUJfuKGEiWLNlGDEGCjKQMLXsqJg8WZuB7pcwK+y/IVGpV+jfJt/TENGJDxKQcQFei3CRpLJirCDeTXDPtUi8hx4ZKt/N7FlWb+uUGFPbg/6Q6mvqLRKtHCq1qg43s/2agPDDcZC3YI6+gYTFAXPwoza1hjrDnZewa+11ecESLaTT8Z6qWGNzvHPFNA/wr88cKhzR4x31rGbYOavULr0n5RI2loPfQUL1JgBn1bsb0AlzdFmP5p5SxPv5CeLrUrzvpf2k2HMm4nre/R7L4g=
