kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: quay-lr
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  labels:
    codefresh.io/entity: integration-secret
    codefresh.io/integration-name: quay-lr
    codefresh.io/integration-type: registry.quay
spec:
  template:
    metadata:
      name: quay-lr
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
    data: null
  encryptedData:
    password: >-
      AgBuD+Y3uXrIECw7etBFsDfYmsf6M//Nw9VrKyQ84J4Kf1fRs5TleNCpjlNRRjbhIMhwvJVfXbc//VDu1/VIg4m0OQ3NCA4zZifYC5BwuQk9kbnsOj1g2u0PzRXXNmyI9s8HhjH0PARqyfRvPBVpjdnG8LBR5EFo6TL6KvNpG3G+zhj7MeDiK3u7vq6QUOYBJX/yOqnB+8DozS3Ew0+j2kIafcGgyTn5aysbZ+484pUJbtThuXhk+17xPJAeIJAPWN99Zh+kaAlN/9Jx0/Vw6iCHdhZYOoUeDBOAwyV5vMJor8sotpPhxRdXXWFcxGiw/H19fsNmCBnwXSgbQ4Dt2R2/AnKFeejhYdg9SEWQ3tGVR1ve+fhwymJLH31DzYIJ/ITFvVTJUSI8dD1cDdJ7kavhWifK0QxDsCxr6KaEd3dMndvvzeiZF4zIzZE5indfSP35PKBE/IWak31FLM0Iu88L+AlzVXC7IyqbD0xWbfe/lV0s8L29/YAhs/Z7BdIT2tIMhWy91KgV5P4b44kzt7ZTcqql0snEBk6i1OY/44BYVUH/t7uQ5mtnNTvRoSN0UwJHH/yvmoJ/2hAUmOypVKnHtZzFx0YdxQGpqapKkxz+EfsRO9+kuNpEypGZ6g8V5xKfUE6B/zULaR2QegzaeGDY8VV6tfntrmRMrpiSc5yaezyXukZ4A39lS/yzULC9Ch81ouVPAMIthNsUP0eEbctKZ/2iBIi0oP1cKfsxaQ==
